// <auto-generated />
using System;
using Books.Data.UnitOfWork.Sql.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Books.Data.UnitOfWork.Sql.Migrations
{
    [DbContext(typeof(BooksSqlDbContext))]
    [Migration("20190929154932_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Books.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Author");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnName("path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47f853c0-f158-49ff-a83a-2fb83c6b6e37"),
                            Author = "Clarke, Arthur C",
                            Path = "books\\clarke_arthur_c_a_space_odissey.pdf",
                            Title = "A Space Odissey"
                        },
                        new
                        {
                            Id = new Guid("8442281d-35d6-46a8-a9f9-c8d0e4c8b93d"),
                            Author = "Heinlein, Robert Anson",
                            Path = "books\\heinlein_robert_anson_a_tenderfoot_in_space.pdf",
                            Title = "A tenderfoot in space"
                        },
                        new
                        {
                            Id = new Guid("e1ba0993-c4f2-4a3f-872c-7c87c4ee3f46"),
                            Author = "Niven, Larry",
                            Path = "books\\niven_larry_a_hole_in_space.pdf",
                            Title = "A Hole in Space"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
