// <auto-generated />
using System;
using Books.Data.UnitOfWork.Sql.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Books.Data.UnitOfWork.Sql.Migrations
{
    [DbContext(typeof(BooksSqlDbContext))]
    partial class BooksSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Books.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Author");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnName("path");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fff3a52-66c5-4f2f-b5d8-2ef7cfeabe37"),
                            Author = "Clarke, Arthur C",
                            Path = "books\\clarke_arthur_c_a_space_odissey.pdf",
                            Status = 2,
                            Title = "A Space Odissey"
                        },
                        new
                        {
                            Id = new Guid("5b193d94-188b-4897-8e56-1823d3f8daca"),
                            Author = "Heinlein, Robert Anson",
                            Path = "books\\heinlein_robert_anson_a_tenderfoot_in_space.pdf",
                            Status = 2,
                            Title = "A tenderfoot in space"
                        },
                        new
                        {
                            Id = new Guid("e841147f-1c94-4699-bdb6-ae55cb0de450"),
                            Author = "Niven, Larry",
                            Path = "books\\niven_larry_a_hole_in_space.pdf",
                            Status = 2,
                            Title = "A Hole in Space"
                        });
                });

            modelBuilder.Entity("Books.Domain.Books.BookSagaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnName("event_data");

                    b.Property<Guid>("SagaId")
                        .HasColumnName("saga_id");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("book_saga");
                });
#pragma warning restore 612, 618
        }
    }
}
