// <auto-generated />
using System;
using Books.Data.UnitOfWork.Sql.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Books.Data.UnitOfWork.Sql.Migrations
{
    [DbContext(typeof(BooksSqlDbContext))]
    partial class BooksSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Books.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Author");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnName("path");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12140792-49f8-4b05-9641-cbd58706961a"),
                            Author = "Clarke, Arthur C",
                            Path = "books\\clarke_arthur_c_a_space_odissey.pdf",
                            Status = 2,
                            Title = "A Space Odissey"
                        },
                        new
                        {
                            Id = new Guid("4359fd53-7f6a-4fdb-af32-d3d552b292c3"),
                            Author = "Heinlein, Robert Anson",
                            Path = "books\\heinlein_robert_anson_a_tenderfoot_in_space.pdf",
                            Status = 2,
                            Title = "A tenderfoot in space"
                        },
                        new
                        {
                            Id = new Guid("1bea3e46-4f9e-4ea7-9713-b646f9c5883c"),
                            Author = "Niven, Larry",
                            Path = "books\\niven_larry_a_hole_in_space.pdf",
                            Status = 2,
                            Title = "A Hole in Space"
                        });
                });

            modelBuilder.Entity("Books.Domain.Events.SagaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnName("data");

                    b.Property<Guid>("SagaId");

                    b.Property<bool>("Success")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.ToTable("saga_event");
                });
#pragma warning restore 612, 618
        }
    }
}
