version: '3.1'

services:

  mongo-one:
    image: mongo:4.0
    command: --bind_ip_all --replSet rs0
    restart: always
    ports:
      - 27017:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      
  mongo-two:
    image: mongo:4.0
    command: --bind_ip_all --replSet rs0
    restart: always
    ports:
      - 27018:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
    # image: mongo-express
    # restart: always
    # ports:
      # - 8081:8081
    # environment:
      # ME_CONFIG_MONGODB_SERVER: dotnetcore-mongodb_mongo-one_1,dotnetcore-mongodb_mongo-two_1
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example

  postgres:
    image: 'postgres:9.6.2'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'

  # postgres-express:
    # image: adminer
    # restart: always
    # ports:
      # - 8080:8080