version: '3.1'

services:
  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017

  postgres:
    image: 'postgres:9.6.2'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'