// <auto-generated />
using System;
using Books.Data.Sql.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Books.Data.Sql.Migrations
{
    [DbContext(typeof(BooksSqlDbContext))]
    [Migration("20190914215932_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Books.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Author");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(255);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("329f93c3-747d-4896-aac6-37d368b4834b"),
                            Author = "Clarke, Arthur C",
                            Name = "A Space Odissey",
                            Path = "books\\clarke_arthur_c_a_space_odissey.pdf"
                        },
                        new
                        {
                            Id = new Guid("71091081-6be2-4263-bbe3-0f7be788064f"),
                            Author = "Heinlein, Robert Anson",
                            Name = "A tenderfoot in space",
                            Path = "books\\heinlein_robert_anson_a_tenderfoot_in_space.pdf"
                        },
                        new
                        {
                            Id = new Guid("14fc72e5-9e63-4b00-8967-dc0303908b3a"),
                            Author = "Niven, Larry",
                            Name = "A Hole in Space",
                            Path = "books\\niven_larry_a_hole_in_space.pdf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
