// <auto-generated />
using System;
using Books.Data.Sql.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Books.Data.Sql.Migrations
{
    [DbContext(typeof(BooksSqlDbContext))]
    [Migration("20190915191945_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Books.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Author");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnName("path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("072fd0ee-16dd-40f7-b0ec-a5585742c08b"),
                            Author = "Clarke, Arthur C",
                            Path = "books\\clarke_arthur_c_a_space_odissey.pdf",
                            Title = "A Space Odissey"
                        },
                        new
                        {
                            Id = new Guid("162cad02-4722-414b-8742-81a7d5c42c96"),
                            Author = "Heinlein, Robert Anson",
                            Path = "books\\heinlein_robert_anson_a_tenderfoot_in_space.pdf",
                            Title = "A tenderfoot in space"
                        },
                        new
                        {
                            Id = new Guid("77f12225-3747-4dc1-a761-09cde1f9ae7f"),
                            Author = "Niven, Larry",
                            Path = "books\\niven_larry_a_hole_in_space.pdf",
                            Title = "A Hole in Space"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
